@startebnf
title Java 20 — IntegerLiteral (INTEIRO)
IntegerLiteral = (DecimalNumeral | HexNumeral | OctalNumeral | BinaryNumeral), [("l" | "L")];
DecimalNumeral = "0" | ? 1-9 ?, [Digits] | ? 1-9 ?, {"_"}-, Digits;
Digits = Digit, [[{Digit | "_"}-], Digit];
HexNumeral = "0", ("x" | "X"), HexDigit, [[{HexDigit | "_"}-], HexDigit];
OctalNumeral = "0", {"_"}, OctalDigit, [[{OctalDigit | "_"}-], OctalDigit];
BinaryNumeral = "0", ("b" | "B"), BinaryDigit, [[{BinaryDigit | "_"}-], BinaryDigit];
@endebnf
